/**
 * NexaMOS Research Audit Event Model
 *
 * Sourced from NexaMOS Blog Phase 2A specifications
 */

export type ResearchEventType =
  | 'RESEARCH_PROJECT_CREATED'
  | 'RESEARCH_STARTED'
  | 'SOURCE_ADDED'
  | 'EVIDENCE_CAPTURED'
  | 'CLAIM_CREATED'
  | 'CLAIM_EVALUATED'
  | 'EVIDENCE_LINKED'
  | 'FINDING_CREATED'
  | 'SYNTHESIS_CREATED'
  | 'RESEARCH_READY'
  | 'RESEARCH_COMPLETED'
  | 'RESEARCH_BLOCKED'
  | 'SOURCE_INGESTION_STARTED'
  | 'SOURCE_PARSED'
  | 'SOURCE_DUPLICATE_DETECTED'
  | 'SOURCE_INGESTED'
  | 'EVIDENCE_EXTRACTION_STARTED'
  | 'EVIDENCE_EXTRACTED'
  | 'DISCOVERY_STARTED'
  | 'DISCOVERY_QUERY_CREATED'
  | 'SOURCE_CANDIDATE_DISCOVERED'
  | 'SOURCE_CANDIDATE_ACCEPTED'
  | 'SOURCE_CANDIDATE_REJECTED'
  | 'SOURCE_ACQUISITION_STARTED'
  | 'SOURCE_ACQUIRED'
  | 'SOURCE_ACQUISITION_FAILED'
  | 'SOURCE_SENT_TO_INGESTION'
  | 'RESEARCH_PLAN_CREATED'
  | 'RESEARCH_ITERATION_STARTED'
  | 'AI_RESEARCH_PROPOSAL_CREATED'
  | 'RESEARCH_NEXT_ACTION_SELECTED'
  | 'RESEARCH_GAP_ANALYZED'
  | 'RESEARCH_STOPPED'
  | 'RESEARCH_BRIEF_CREATED'
  | 'HUMAN_REVIEW_REQUESTED';

export const RESEARCH_EVENT_TYPES: readonly ResearchEventType[] = [
  'RESEARCH_PROJECT_CREATED',
  'RESEARCH_STARTED',
  'SOURCE_ADDED',
  'EVIDENCE_CAPTURED',
  'CLAIM_CREATED',
  'CLAIM_EVALUATED',
  'EVIDENCE_LINKED',
  'FINDING_CREATED',
  'SYNTHESIS_CREATED',
  'RESEARCH_READY',
  'RESEARCH_COMPLETED',
  'RESEARCH_BLOCKED',
  'SOURCE_INGESTION_STARTED',
  'SOURCE_PARSED',
  'SOURCE_DUPLICATE_DETECTED',
  'SOURCE_INGESTED',
  'EVIDENCE_EXTRACTION_STARTED',
  'EVIDENCE_EXTRACTED',
  'DISCOVERY_STARTED',
  'DISCOVERY_QUERY_CREATED',
  'SOURCE_CANDIDATE_DISCOVERED',
  'SOURCE_CANDIDATE_ACCEPTED',
  'SOURCE_CANDIDATE_REJECTED',
  'SOURCE_ACQUISITION_STARTED',
  'SOURCE_ACQUIRED',
  'SOURCE_ACQUISITION_FAILED',
  'SOURCE_SENT_TO_INGESTION',
  'RESEARCH_PLAN_CREATED',
  'RESEARCH_ITERATION_STARTED',
  'AI_RESEARCH_PROPOSAL_CREATED',
  'RESEARCH_NEXT_ACTION_SELECTED',
  'RESEARCH_GAP_ANALYZED',
  'RESEARCH_STOPPED',
  'RESEARCH_BRIEF_CREATED',
  'HUMAN_REVIEW_REQUESTED'
] as const;

export interface ResearchEvent {
  id: string;
  projectId: string;
  type: ResearchEventType;
  timestamp: string; // ISO 8601 string
  actor: string; // Identifier or name of the actor
  summary: string; // Concise factual description
  metadata?: Record<string, unknown> | null;
}
